name: Close issues related to a merged pull request on master branch.

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  closeIssueOnPrMergeTrigger:

    runs-on: ubuntu-latest

    steps:
      - name: Closes issues related to a merged pull request.
        uses: knatch/gha-mjolnir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
